export const projects = [
  {
    index: "01",
    label: "Xervsware",
    description: "A team that loves to build tech solutions.",
    image: "/xervsware.svg",
    url: "https://www.xervsware.com",
  },
  {
    index: "02",
    label: "Monarca",
    description: "A landing page for a package delivery company.",
    image: "/monarca.svg",
    url: "https://diegoes.vercel.app/projects",
  },
  {
    index: "03",
    label: "Shisho Baby Clothes",
    description: "An eccommerce site for baby clothes.",
    image: "/shisho.png",
    url: "https://shishobabyclothes.ae",
  },
  {
    index: "04",
    label: "Ad Astra",
    description: "A mental health app for astronomy enthusiasts.",
    image: "/adastra.svg",
    url: "https://expo.dev/@ghastly/ad-astra",
  },
  {
    index: "05",
    label: "Touch Room",
    description: "An interactive game for special moments.",
    image: "/touch.png",
    url: "https://touch-room.vercel.app",
  },
  {
    index: "06",
    label: "GEA",
    description: "A platform for software engineering students.",
    image: "/gea.svg",
    url: "https://gea-platform.vercel.app",
  },
  {
    index: "07",
    label: "GEITS",
    description: "A platform for engineering students.",
    image: "/geits.svg",
    url: "https://geits.tech",
  },
  {
    index: "08",
    label: "Campanario",
    description: "A site for event information and booking.",
    image: "/campanario.svg",
    url: "https://campanario-eventos.vercel.app",
  },
];
